#!/bin/bash

echo "overwriting docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME ."

echo "docker build -f Dockerfile --build-arg VERSION=${DOCKER_TAG} -t ${IMAGE_NAME} ."
docker build -f Dockerfile --build-arg VERSION=${DOCKER_TAG} -t ${IMAGE_NAME} .
