<?php
/**
 * phpDocumentor
 *
 * PHP Version 5.3
 *
 * @author    Mike van Riel <mike.vanriel@naenius.com>
 * @copyright 2010-2012 Mike van Riel / Naenius (http://www.naenius.com)
 * @license   http://www.opensource.org/licenses/mit-license.php MIT
 * @link      http://phpdoc.org
 */

namespace phpDocumentor\Plugin\Twig;

use \phpDocumentor\Transformer\Transformation;

/**
 * An interface shared by all Twig interfaces intended for phpDocumentor.
 *
 * @author    Mike van Riel <mike.vanriel@naenius.com>
 * @copyright 2010-2012 Mike van Riel / Naenius (http://www.naenius.com)
 * @license   http://www.opensource.org/licenses/mit-license.php MIT
 */
interface ExtensionInterface
{
    /**
     * Registers the structure and transformation objects with this extension.
     *
     * The Structure and Transformation object can be used to get context from
     * and to provide additional information.
     *
     * @param \SimpleXMLElement $structure      Represents the complete Abstract
     *     Syntax Tree as generated by phpDocumentor
     * @param Transformation    $transformation Represents the transformation
     *     meta data used in the current generation cycle.
     */
    public function __construct(
        \SimpleXMLElement $structure, Transformation $transformation
    );
}
