jms_serializer:
    visitors:
        json:
            options:
                - JSON_UNESCAPED_SLASHES
                - JSON_PRESERVE_ZERO_FRACTION
        xml:
            format_output: '%kernel.debug%'
    metadata:
        cache: file
        debug: "%kernel.debug%"
        auto_detection: false
        file_cache:
            dir: "/tmp/php-doc/cache/jms_serializer"
