monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "/tmp/php-doc/log/phar.log"
            level: debug
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
            verbosity_levels:
               VERBOSITY_NORMAL: INFO
               VERBOSITY_VERBOSE: INFO
