<?xml version="1.0"?>

<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output indent="yes" method="html" />

    <xsl:template name="sidebar-footer">
        Documentation is generated by <a href="http://docblox-project.org" target="_top">
        <img src="{$root}images/icon48x48.png" height="12" align="top" alt="Logo"/> DocBlox <xsl:value-of select="$version" />
        </a>, images courtesy of <a href="http://glyphish.com/" target="_top">Glyphish</a>
    </xsl:template>

</xsl:stylesheet>