<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output indent="yes" method="html" />
  <xsl:include href="../default/file.xsl" />
  <xsl:include href="../frames/chrome.xsl" />
  <xsl:include href="page_header.xsl" />

  <xsl:template match="/project">
    <xsl:call-template name="page_header" />

    <div class="content">
      <h2>Welcome to Zend Framework!</h2>
      This documentation was generated by <a href="http://www.docblox-project.org">DocBlox</a>
    </div>
  </xsl:template>

</xsl:stylesheet>